version: 2.1

orbs:
  docker: circleci/docker@1.4.0

workflows:
  version: 2
  build:
    jobs:
      - docker/publish:
          context: onesignal-global
          image: "osig/prometheus-cloudflare-exporter"
          before_build:
            - attach_workspace:
                at: ./
          tag: "$CIRCLE_TAG"
          dockerfile: "Dockerfile"
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
